-- 1. Create consumer role
USE ROLE ACCOUNTADMIN;
-- Enable cross region inference (required to use claude-4-sonnet)
ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';
-- Create consumer role
CREATE ROLE IF NOT EXISTS AI_CICD_RL;
GRANT ROLE AI_CICD_RL TO ROLE ACCOUNTADMIN;

GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE AI_CICD_rl;
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE AI_CICD_RL;
SET my_user = CURRENT_USER();
GRANT ROLE AI_CICD_RL to user IDENTIFIER($my_user);
CREATE USER IF NOT EXISTS GH_ACTION_USER TYPE = SERVICE;

GRANT ROLE AI_CICD_RL TO USER GH_ACTION_USER;
-- 2. Create database, schema, and warehouse
CREATE DATABASE IF NOT EXISTS AI_CICD;
CREATE SCHEMA IF NOT EXISTS AI_CICD.AGENTIC_AI;
USE SCHEMA AI_CICD.AGENTIC_AI;
GRANT ALL ON SCHEMA AI_CICD.agentic_ai TO ROLE AI_CICD_RL;

-- A User for Github
CREATE AUTHENTICATION POLICY IF NOT EXISTS PAT_ALLOW
  PAT_POLICY=(
    NETWORK_POLICY_EVALUATION = NOT_ENFORCED
  );
ALTER USER GH_ACTION_USER SET AUTHENTICATION POLICY PAT_ALLOW;


-- AI_CICD Database
GRANT ALL ON DATABASE AI_CICD TO ROLE AI_CICD_RL;
GRANT USAGE ON SCHEMA AI_CICD.AGENTIC_AI TO ROLE AI_CICD_RL;
GRANT SELECT ON ALL TABLES IN SCHEMA AI_CICD.AGENTIC_AI TO ROLE AI_CICD_RL;
GRANT SELECT ON FUTURE TABLES IN SCHEMA AI_CICD.AGENTIC_AI TO ROLE AI_CICD_RL;
GRANT CREATE TABLE ON SCHEMA AI_CICD.AGENTIC_AI TO ROLE AI_CICD_RL;
-- Snowflake Database
GRANT DATABASE ROLE SNOWFLAKE.GOVERNANCE_VIEWER TO ROLE AI_CICD_RL;
-- Cortex Search Service
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA AI_CICD.AGENTIC_AI TO ROLE AI_CICD_RL;
-- Cortex Agent 
GRANT CREATE AGENT ON SCHEMA AI_CICD.AGENTIC_AI TO ROLE AI_CICD_RL;
-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS AI_CICD_WH
WITH 
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 3600
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = FALSE
COMMENT = 'TechUp Warehouse with 1-hour auto-suspend policy';
GRANT USAGE, OPERATE ON WAREHOUSE AI_CICD_wh TO ROLE AI_CICD_RL;

-- 3. Create tables for sales data
USE ROLE AI_CICD_RL;
CREATE SCHEMA IF NOT EXISTS AI_CICD.DEV_AGENTIC_AI;
CREATE SCHEMA IF NOT EXISTS AI_CICD.TEST_AGENTIC_AI;
CREATE SCHEMA IF NOT EXISTS AI_CICD.PROD_AGENTIC_AI;
USE SCHEMA AI_CICD.AGENTIC_AI;

-- Create the physical table structure
CREATE OR REPLACE TABLE QUERY_HISTORY_MATERIALIZED (
    -- Core Query Identification
    QUERY_ID VARCHAR(16777216),
    QUERY_TEXT STRING,
    QUERY_TYPE VARCHAR(16777216),
    QUERY_HASH VARCHAR(16777216),
    QUERY_PARAMETERIZED_HASH VARCHAR(16777216),
    QUERY_TAG VARCHAR(16777216),
    
    -- User & Security Context
    USER_NAME VARCHAR(16777216),
    ROLE_NAME VARCHAR(16777216),
    USER_TYPE VARCHAR(16777216),
    
    -- Infrastructure Context  
    DATABASE_NAME VARCHAR(16777216),
    SCHEMA_NAME VARCHAR(16777216),
    WAREHOUSE_NAME VARCHAR(16777216),
    WAREHOUSE_SIZE VARCHAR(16777216),
    WAREHOUSE_TYPE VARCHAR(16777216),
    
    -- Execution Context
    START_TIME TIMESTAMP_LTZ(6),
    END_TIME TIMESTAMP_LTZ(6),
    TOTAL_ELAPSED_TIME NUMBER(38,0),
    EXECUTION_TIME NUMBER(38,0),
    COMPILATION_TIME NUMBER(38,0),
    EXECUTION_STATUS VARCHAR(16777216),
    ERROR_CODE VARCHAR(16777216),
    ERROR_MESSAGE STRING,
    
    -- Performance Metrics
    BYTES_SCANNED NUMBER(38,0),
    BYTES_WRITTEN NUMBER(38,0),
    BYTES_DELETED NUMBER(38,0),
    ROWS_PRODUCED NUMBER(38,0),
    ROWS_INSERTED NUMBER(38,0),
    ROWS_UPDATED NUMBER(38,0),
    ROWS_DELETED NUMBER(38,0),
    ROWS_UNLOADED NUMBER(38,0),
    PERCENTAGE_SCANNED_FROM_CACHE NUMBER(38,3),
    
    -- Cost Metrics
    CREDITS_USED_CLOUD_SERVICES NUMBER(38,9),
    
    -- Data Transfer
    INBOUND_DATA_TRANSFER_BYTES NUMBER(38,0),
    OUTBOUND_DATA_TRANSFER_BYTES NUMBER(38,0),
    INBOUND_DATA_TRANSFER_CLOUD VARCHAR(16777216),
    INBOUND_DATA_TRANSFER_REGION VARCHAR(16777216),
    OUTBOUND_DATA_TRANSFER_CLOUD VARCHAR(16777216),
    OUTBOUND_DATA_TRANSFER_REGION VARCHAR(16777216),
    
    -- Memory & Spill
    BYTES_SPILLED_TO_LOCAL_STORAGE NUMBER(38,0),
    BYTES_SPILLED_TO_REMOTE_STORAGE NUMBER(38,0),
    BYTES_READ_FROM_RESULT NUMBER(38,0),
    BYTES_SENT_OVER_THE_NETWORK NUMBER(38,0),
    BYTES_WRITTEN_TO_RESULT NUMBER(38,0),
    
    -- Advanced Metrics
    PARTITIONS_SCANNED NUMBER(38,0),
    PARTITIONS_TOTAL NUMBER(38,0),
    QUERY_LOAD_PERCENT NUMBER(38,3),
    CLUSTER_NUMBER NUMBER(38,0),
    
    -- Queue & Wait Times
    QUEUED_OVERLOAD_TIME NUMBER(38,0),
    QUEUED_PROVISIONING_TIME NUMBER(38,0),
    QUEUED_REPAIR_TIME NUMBER(38,0),
    CHILD_QUERIES_WAIT_TIME NUMBER(38,0),
    
    -- System Context
    SESSION_ID NUMBER(38,0),
    TRANSACTION_ID NUMBER(38,0),
    TRANSACTION_BLOCKED_TIME NUMBER(38,0),
    RELEASE_VERSION VARCHAR(16777216),
    
    -- External Functions
    EXTERNAL_FUNCTION_TOTAL_INVOCATIONS NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_SENT_ROWS NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_RECEIVED_ROWS NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_SENT_BYTES NUMBER(38,0),
    EXTERNAL_FUNCTION_TOTAL_RECEIVED_BYTES NUMBER(38,0),
    
    -- Additional Context
    IS_CLIENT_GENERATED_STATEMENT BOOLEAN,
    QUERY_RETRY_CAUSE VARCHAR(16777216),
    QUERY_RETRY_TIME NUMBER(38,0),
    FAULT_HANDLING_TIME NUMBER(38,0),
    LIST_EXTERNAL_FILES_TIME NUMBER(38,0),
    
    -- Search-Optimized Fields
    SEARCH_METADATA STRING,
    QUERY_SUMMARY STRING,
    PERFORMANCE_CATEGORY VARCHAR(50),
    COST_CATEGORY VARCHAR(50),
    
    -- Metadata
    MATERIALIZED_AT TIMESTAMP_NTZ
);

-- Populate with 60 days of data
INSERT INTO QUERY_HISTORY_MATERIALIZED
SELECT 
    -- Core Query Identification
    QUERY_ID,
    QUERY_TEXT,
    QUERY_TYPE,
    QUERY_HASH,
    QUERY_PARAMETERIZED_HASH,
    QUERY_TAG,
    
    -- User & Security Context
    USER_NAME,
    ROLE_NAME,
    USER_TYPE,
    
    -- Infrastructure Context  
    DATABASE_NAME,
    SCHEMA_NAME,
    WAREHOUSE_NAME,
    WAREHOUSE_SIZE,
    WAREHOUSE_TYPE,
    
    -- Execution Context
    START_TIME,
    END_TIME,
    TOTAL_ELAPSED_TIME,
    EXECUTION_TIME,
    COMPILATION_TIME,
    EXECUTION_STATUS,
    ERROR_CODE,
    ERROR_MESSAGE,
    
    -- Performance Metrics
    BYTES_SCANNED,
    BYTES_WRITTEN,
    BYTES_DELETED,
    ROWS_PRODUCED,
    ROWS_INSERTED,
    ROWS_UPDATED,
    ROWS_DELETED,
    ROWS_UNLOADED,
    PERCENTAGE_SCANNED_FROM_CACHE,
    
    -- Cost Metrics
    CREDITS_USED_CLOUD_SERVICES,
    
    -- Data Transfer
    INBOUND_DATA_TRANSFER_BYTES,
    OUTBOUND_DATA_TRANSFER_BYTES,
    INBOUND_DATA_TRANSFER_CLOUD,
    INBOUND_DATA_TRANSFER_REGION,
    OUTBOUND_DATA_TRANSFER_CLOUD,
    OUTBOUND_DATA_TRANSFER_REGION,
    
    -- Memory & Spill
    BYTES_SPILLED_TO_LOCAL_STORAGE,
    BYTES_SPILLED_TO_REMOTE_STORAGE,
    BYTES_READ_FROM_RESULT,
    BYTES_SENT_OVER_THE_NETWORK,
    BYTES_WRITTEN_TO_RESULT,
    
    -- Advanced Metrics
    PARTITIONS_SCANNED,
    PARTITIONS_TOTAL,
    QUERY_LOAD_PERCENT,
    CLUSTER_NUMBER,
    
    -- Queue & Wait Times
    QUEUED_OVERLOAD_TIME,
    QUEUED_PROVISIONING_TIME,
    QUEUED_REPAIR_TIME,
    CHILD_QUERIES_WAIT_TIME,
    
    -- System Context
    SESSION_ID,
    TRANSACTION_ID,
    TRANSACTION_BLOCKED_TIME,
    RELEASE_VERSION,
    
    -- External Functions
    EXTERNAL_FUNCTION_TOTAL_INVOCATIONS,
    EXTERNAL_FUNCTION_TOTAL_SENT_ROWS,
    EXTERNAL_FUNCTION_TOTAL_RECEIVED_ROWS,
    EXTERNAL_FUNCTION_TOTAL_SENT_BYTES,
    EXTERNAL_FUNCTION_TOTAL_RECEIVED_BYTES,
    
    -- Additional Context
    IS_CLIENT_GENERATED_STATEMENT,
    QUERY_RETRY_CAUSE,
    QUERY_RETRY_TIME,
    FAULT_HANDLING_TIME,
    LIST_EXTERNAL_FILES_TIME,
    
    -- Derived Searchable Fields
    CONCAT_WS(' | ',
        COALESCE(QUERY_TYPE, 'UNKNOWN'),
        COALESCE(DATABASE_NAME, 'NO_DB'),
        COALESCE(SCHEMA_NAME, 'NO_SCHEMA'),
        COALESCE(USER_NAME, 'NO_USER'),
        COALESCE(ROLE_NAME, 'NO_ROLE'),
        COALESCE(WAREHOUSE_NAME, 'NO_WAREHOUSE'),
        CASE WHEN ERROR_CODE IS NOT NULL THEN 'ERROR' ELSE 'SUCCESS' END,
        CASE 
            WHEN TOTAL_ELAPSED_TIME > 300000 THEN 'LONG_RUNNING'
            WHEN TOTAL_ELAPSED_TIME > 30000 THEN 'MEDIUM_DURATION'
            ELSE 'QUICK'
        END,
        CASE
            WHEN CREDITS_USED_CLOUD_SERVICES > 0.1 THEN 'HIGH_COST'
            WHEN CREDITS_USED_CLOUD_SERVICES > 0.01 THEN 'MEDIUM_COST'
            WHEN CREDITS_USED_CLOUD_SERVICES > 0 THEN 'LOW_COST'
            ELSE 'MINIMAL_COST'
        END
    ) AS SEARCH_METADATA,
    
    -- Human-readable query summary
    CONCAT(
        'Query Type: ', COALESCE(QUERY_TYPE, 'Unknown'), ' | ',
        'User: ', COALESCE(USER_NAME, 'Unknown'), ' | ',
        'Role: ', COALESCE(ROLE_NAME, 'Unknown'), ' | ',
        'Database: ', COALESCE(DATABASE_NAME, 'None'), ' | ',
        'Warehouse: ', COALESCE(WAREHOUSE_NAME, 'None'), ' | ',
        'Duration: ', COALESCE(ROUND(TOTAL_ELAPSED_TIME/1000, 2), 0), ' seconds | ',
        'Status: ', COALESCE(EXECUTION_STATUS, 'Unknown'), ' | ',
        'Data Scanned: ', COALESCE(ROUND(BYTES_SCANNED/POWER(1024,3), 2), 0), ' GB | ',
        'Credits: ', COALESCE(ROUND(CREDITS_USED_CLOUD_SERVICES, 4), 0)
    ) AS QUERY_SUMMARY,
    
    -- Performance categorization
    CASE 
        WHEN TOTAL_ELAPSED_TIME > 300000 THEN 'LONG_RUNNING'
        WHEN TOTAL_ELAPSED_TIME > 30000 THEN 'MEDIUM_DURATION'
        WHEN TOTAL_ELAPSED_TIME > 5000 THEN 'QUICK'
        ELSE 'INSTANT'
    END AS PERFORMANCE_CATEGORY,
    
    -- Cost categorization
    CASE
        WHEN CREDITS_USED_CLOUD_SERVICES > 1.0 THEN 'VERY_EXPENSIVE'
        WHEN CREDITS_USED_CLOUD_SERVICES > 0.1 THEN 'EXPENSIVE'
        WHEN CREDITS_USED_CLOUD_SERVICES > 0.01 THEN 'MODERATE'
        WHEN CREDITS_USED_CLOUD_SERVICES > 0 THEN 'LOW_COST'
        ELSE 'FREE'
    END AS COST_CATEGORY,
    
    -- Materialization timestamp
    CURRENT_TIMESTAMP() AS MATERIALIZED_AT

FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= CURRENT_DATE - INTERVAL '14 DAYS'
  AND START_TIME < CURRENT_DATE  -- Avoid partial current day
ORDER BY START_TIME DESC
LIMIT 1000
;

USE ROLE ACCOUNTADMIN;
-- If the below fails to run, you may need to accept marketplace terms before proceeding
CREATE DATABASE IF NOT EXISTS IDENTIFIER('"SNOWFLAKE_DOCUMENTATION"') FROM LISTING IDENTIFIER('"GZSTZ67BY9OQ4"');
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE_DOCUMENTATION TO ROLE AI_CICD_RL;

-- Use the below for the Github Action secret
ALTER USER GH_ACTION_USER ADD PROGRAMMATIC ACCESS TOKEN GH_ACTION_PAT2
ROLE_RESTRICTION = 'AI_CICD_RL'; -- This will be shortlived by default

-- 9. Cleanup Script
-- Run this section to remove all resources created above
-- USE ROLE ACCOUNTADMIN;
-- DROP USER IF EXISTS GH_ACTION_USER;
-- DROP AUTHENTICATION POLICY AI_CICD.AGENTIC_AI.PAT_ALLOW;
-- DROP DATABASE IF EXISTS AI_CICD;
-- DROP ROLE IF EXISTS AI_CICD_RL;